### ISSUE TITLE
[Support] [DumbQuestion] RE: CKAN badge.

### ISSUE THREAD

**Issue by 602p** [KerbalStuff/KerbalStuff#96]
Can someone explain the CKAN badge? How do I apply it to a project? Does it seperatley register the mod? What's the deal?

I'm familiar with CKAN ( I :heart: it ,) just confused at the KerbalStuff badge for it.

If I missed a help page somewhere, sorry, just point me at it :/

**Comment by SirCmpwn** [comment]
The CKAN badge is in place for mods that are listed in CKAN. New mods are automatically submitted to CKAN upon creation. If you have a mod that was created prior to CKAN integration and you want the CKAN badge added, then you can request that special.

Closing this issue because it's not actionable, but feel free to continue the discussion.
